version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/static/uploads
      - ./certs:/app/certs
    environment:
      - HOST_IP=${HOST_IP:-localhost}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-changeme}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-changeme}
      - MAX_UPLOAD_SIZE=${MAX_UPLOAD_SIZE:-100000000}
      - SESSION_LIFETIME_MINUTES=${SESSION_LIFETIME_MINUTES:-30}
      - CACHE_TYPE=${CACHE_TYPE:-simple}
      - CACHE_DEFAULT_TIMEOUT=${CACHE_DEFAULT_TIMEOUT:-300}
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q 'status.*green'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  elasticsearch_data: 