version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/static/uploads
      - ./certs:/app/certs
      - ./data:/app/data
    environment:
      - HOST_IP=${HOST_IP:-localhost}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-changeme}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-changeme}
      - MAX_UPLOAD_SIZE=${MAX_UPLOAD_SIZE:-100000000}
      - SESSION_LIFETIME_MINUTES=${SESSION_LIFETIME_MINUTES:-30}
      - CACHE_TYPE=${CACHE_TYPE:-simple}
      - CACHE_DEFAULT_TIMEOUT=${CACHE_DEFAULT_TIMEOUT:-300}
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - REMOTE_BACKUP_FOLDER=/remote/backup
      - COMPRESSION_THRESHOLD=10485760
      - COMPRESSION_METHOD=7z
      - SSL_CERT_PATH=/app/certs/cert.pem
      - SSL_KEY_PATH=/app/certs/key.pem
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges:true
      - no-suid:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/run
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -XX:+UseG1GC -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=20"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q 'status.*green'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges:true
      - no-suid:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/run
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

volumes:
  elasticsearch_data:
    driver: local 