services:
  flask-upload:
    build:
      context: .
    ports:
      - "${APP_PORT:-5000}:${CONTAINER_PORT:-5000}"
    environment:
      - HOST_IP=${HOST_IP:-127.0.0.1}
    volumes:
      - "${UPLOAD_DIR:-/mnt/share/uploads}:/app/static/uploads"
